# Generated by Django 6.0.3 on 2026-03-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='eta_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('assistance_dispatched', 'Assistance Dispatched'), ('resolved', 'Resolved')], default='reported', max_length=30),
        ),
        migrations.AddField(
            model_name='incident',
            name='support_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
